language: node_js
node_js:
- '8'
services:
- docker
cache:
  directories:
  - $HOME/google-cloud-sdk
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_d719442f9bd4_key -iv $encrypted_d719442f9bd4_iv
  -in scripts/secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- chmod 600 github_deploy_key
- eval $(ssh-agent -s)
- ssh-add github_deploy_key
before_script:
- yarn start &
after_script:
- bash scripts/build.sh
- bash scripts/deploy.sh
